"""One-time (re-runnable) setup: Cloudflare Worker + D1 + KV, GitHub repo + secrets.

Reads keys from ../.env, never prints them. Requires: `npx wrangler login` done, PyNaCl installed.
Usage: .venv/bin/python scripts/setup.py [--skip-github] [--skip-worker]
"""
from __future__ import annotations

import base64
import json
import re
import secrets
import subprocess
import sys
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
WORKER = ROOT / "worker"
ENV_FILE = ROOT / ".env"
REPO_NAME = "naya-news-autopilot"
GH_API = "https://api.github.com"


def load_env() -> dict:
    env = {}
    for line in ENV_FILE.read_text().splitlines():
        m = re.match(r"^([A-Z_]+)=(.*)$", line.strip())
        if m:
            env[m.group(1)] = m.group(2).strip()
    return env


def save_env_value(key: str, value: str) -> None:
    text = ENV_FILE.read_text()
    if re.search(rf"^{key}=", text, re.M):
        text = re.sub(rf"^{key}=.*$", f"{key}={value}", text, flags=re.M)
    else:
        text = text.rstrip("\n") + f"\n\n# Generated by setup - shared secret between Worker and GitHub Actions\n{key}={value}\n"
    ENV_FILE.write_text(text)


def wrangler(*args: str, stdin: str | None = None, check: bool = True) -> str:
    res = subprocess.run(["npx", "wrangler", *args], cwd=WORKER, input=stdin, text=True, capture_output=True)
    out = res.stdout + res.stderr
    if check and res.returncode != 0:
        raise SystemExit(f"wrangler {' '.join(args[:3])} failed:\n{out[-1500:]}")
    return out


def setup_worker(env: dict) -> str:
    toml_path = WORKER / "wrangler.toml"
    toml = toml_path.read_text()
    if "REPLACE_D1_ID" in toml:
        listing = json.loads(wrangler("d1", "list", "--json"))
        db = next((d for d in listing if d["name"] == "naya-news-db"), None)
        if not db:
            wrangler("d1", "create", "naya-news-db")
            listing = json.loads(wrangler("d1", "list", "--json"))
            db = next(d for d in listing if d["name"] == "naya-news-db")
        toml = toml.replace("REPLACE_D1_ID", db["uuid"])
        print("D1 database ready")
    if "REPLACE_KV_ID" in toml:
        out = wrangler("kv", "namespace", "list")
        spaces = json.loads(out[out.index("["):])
        ns = next((n for n in spaces if n["title"].endswith("IMAGES") or n["title"] == "naya-news-images"), None)
        if not ns:
            wrangler("kv", "namespace", "create", "naya-news-images")
            out = wrangler("kv", "namespace", "list")
            spaces = json.loads(out[out.index("["):])
            ns = next(n for n in spaces if n["title"] == "naya-news-images")
        toml = toml.replace("REPLACE_KV_ID", ns["id"])
        print("KV namespace ready")
    toml_path.write_text(toml)

    wrangler("d1", "execute", "naya-news-db", "--remote", "--file", "schema.sql", "--yes")
    wrangler("d1", "execute", "naya-news-db", "--remote", "--file", "seed.sql", "--yes")
    print("Database tables and starter feeds ready")

    out = wrangler("deploy")
    m = re.search(r"https://[\w.-]+\.workers\.dev", out)
    if not m:
        raise SystemExit("Deploy finished but no workers.dev URL was printed:\n" + out[-1500:])
    url = m.group(0)
    for name in ("DASHBOARD_PASSWORD", "PIPELINE_SECRET", "BUFFER_API_KEY", "GH_TOKEN", "QUEUE_URL"):
        if env.get(name):
            wrangler("secret", "put", name, stdin=env[name])
    print(f"Worker deployed and secrets set: {url}")
    return url


def gh(method: str, path: str, token: str, **kw) -> requests.Response:
    return requests.request(method, GH_API + path, timeout=30, headers={
        "Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"}, **kw)


def seal(public_key_b64: str, value: str) -> str:
    from nacl import encoding, public
    box = public.SealedBox(public.PublicKey(public_key_b64.encode(), encoding.Base64Encoder()))
    return base64.b64encode(box.encrypt(value.encode())).decode()


def setup_github(env: dict, worker_url: str | None) -> None:
    token = env["GH_TOKEN"]
    user = gh("GET", "/user", token)
    user.raise_for_status()
    owner = user.json()["login"]
    repo = f"{owner}/{REPO_NAME}"
    if gh("GET", f"/repos/{repo}", token).status_code == 404:
        r = gh("POST", "/user/repos", token, json={
            "name": REPO_NAME, "private": False, "has_issues": False, "has_wiki": False,
            "description": "Free automated news-to-social posting pipeline (Naya News)"})
        r.raise_for_status()
        print(f"Created repository {repo}")

    subprocess.run(["git", "add", "-A"], cwd=ROOT, check=True)
    subprocess.run(["git", "-c", "user.name=Naya News Autopilot", "-c", f"user.email={owner}@users.noreply.github.com",
                    "commit", "-q", "-m", "Update Naya News Autopilot"], cwd=ROOT)
    auth = base64.b64encode(f"x-access-token:{token}".encode()).decode()
    push = subprocess.run(["git", "-c", f"http.extraHeader=Authorization: Basic {auth}", "push", "-q",
                           f"https://github.com/{repo}.git", "HEAD:main"], cwd=ROOT, capture_output=True, text=True)
    if push.returncode != 0:
        raise SystemExit("git push failed: " + push.stderr.replace(token, "***")[-800:])
    print("Code pushed to GitHub")

    key = gh("GET", f"/repos/{repo}/actions/secrets/public-key", token).json()
    for name in ("PIPELINE_SECRET", "GEMINI_API_KEY", "QUEUE_URL"):
        if env.get(name):
            r = gh("PUT", f"/repos/{repo}/actions/secrets/{name}", token,
                   json={"encrypted_value": seal(key["key"], env[name]), "key_id": key["key_id"]})
            r.raise_for_status()
    if worker_url:
        r = gh("PATCH", f"/repos/{repo}/actions/variables/WORKER_URL", token, json={"name": "WORKER_URL", "value": worker_url})
        if r.status_code == 404:
            gh("POST", f"/repos/{repo}/actions/variables", token, json={"name": "WORKER_URL", "value": worker_url}).raise_for_status()
    print("GitHub secrets and variables set")


def main() -> None:
    env = load_env()
    missing = [k for k in ("GEMINI_API_KEY", "BUFFER_API_KEY", "GH_TOKEN", "DASHBOARD_PASSWORD") if not env.get(k)]
    if missing:
        raise SystemExit("Fill these in .env first: " + ", ".join(missing))
    if not env.get("PIPELINE_SECRET"):
        env["PIPELINE_SECRET"] = secrets.token_urlsafe(32)
        save_env_value("PIPELINE_SECRET", env["PIPELINE_SECRET"])
    worker_url = None
    if "--skip-worker" not in sys.argv:
        worker_url = setup_worker(env)
        save_env_value("WORKER_URL", worker_url)
    else:
        worker_url = env.get("WORKER_URL")
    if "--skip-github" not in sys.argv:
        setup_github(env, worker_url)
    print("Setup complete.")


if __name__ == "__main__":
    main()
