name = "naya-news-autopilot"
main = "src/index.js"
compatibility_date = "2025-09-01"
workers_dev = true

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "IMAGES"
id = "997a7c301dd84f94a1cb02db9ab93c6b"

[[d1_databases]]
binding = "DB"
database_name = "naya-news-db"
database_id = "59020b9f-7a6f-4fcb-85f4-fa78bc6983c3"

[triggers]
crons = ["*/5 * * * *"]

[vars]
GH_REPO = "ubaid792792/naya-news-autopilot"
GH_WORKFLOW = "pipeline.yml"
GH_REF = "main"

[observability]
enabled = true
